FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
ARG REACT_APP_BACKEND_URL

ENV REACT_APP_BACKEND_URL $REACT_APP_BACKEND_URL
RUN npm run build

EXPOSE 3000
CMD ["node","src/server.js"]
