version: "3.8"

services:
  frontend:
    container_name: frontend-c
    image: frontend-i
    build: ./frontend
    ports:
      - 8080:80
    environment:
      - BACKEND_URL=${BACKEND_URL}

  backend:
    build: ./backend
    container_name: backend-c
    image: backend-i
    ports:
      - 8081:8000
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data: