repos:
- repo: local
  hooks:
  -   id: tests
      name: run tests
      entry: /Users/sam.fallowfield/Documents/python/souper-web-scraping/backend/run-tests.sh
      language: system
      types: [python]
      stages: [commit]
