"""add neutral language column to table

Revision ID: 06dcd68024ca
Revises: a363f59d034e
Create Date: 2023-08-31 15:31:34.030264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dcd68024ca'
down_revision = 'a363f59d034e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('neutral_language_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'neutral_language_percent')
    # ### end Alembic commands ###
