"""add feedback language percentage

Revision ID: 08ddf28cb361
Revises: 106ff76da94a
Create Date: 2023-08-30 16:38:26.013055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ddf28cb361'
down_revision = '106ff76da94a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('positive_language_percent', sa.Integer(), nullable=True))
    op.add_column('section', sa.Column('constructive_language_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'constructive_language_percent')
    op.drop_column('section', 'positive_language_percent')
    # ### end Alembic commands ###
