"""change data type to float

Revision ID: 1c3fcbc15477
Revises: 08ddf28cb361
Create Date: 2023-08-30 16:58:36.435159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3fcbc15477'
down_revision = '08ddf28cb361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
