"""Removed feedback column from section and created separate table with feedback type

Revision ID: 45d5c7e4fa53
Revises: e1430be9db45
Create Date: 2023-07-31 16:01:03.529100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d5c7e4fa53'
down_revision = 'e1430be9db45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
