"""Nullable report columns

Revision ID: 61c05288192f
Revises: af787317717c
Create Date: 2023-07-20 13:29:40.957036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c05288192f'
down_revision = 'af787317717c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'assessment_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('report', 'overall_verdict',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('report', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('report', 'overall_verdict',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('report', 'assessment_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
