"""Alembic commit

Revision ID: 823ef3f899d1
Revises: 8e4c145587a3
Create Date: 2023-07-12 14:29:25.649440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823ef3f899d1'
down_revision = '8e4c145587a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
