"""Sections unique constraint

Revision ID: a2b4b15fd4ff
Revises: 1143610c6ffb
Create Date: 2023-07-21 09:38:23.754587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b4b15fd4ff'
down_revision = '1143610c6ffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('section_report_id_number_key', 'section', ['report_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_report_id_number_key', 'section', type_='unique')
    # ### end Alembic commands ###
