"""add feedback percentage to the section table

Revision ID: a363f59d034e
Revises: c2010fea1867
Create Date: 2023-08-31 14:35:41.192691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a363f59d034e'
down_revision = 'c2010fea1867'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('positive_language_percent', sa.Float(), nullable=True))
    op.add_column('section', sa.Column('constructive_language_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'constructive_language_percent')
    op.drop_column('section', 'positive_language_percent')
    # ### end Alembic commands ###
