"""Unique constraint on report url

Revision ID: af787317717c
Revises: e04f09912951
Create Date: 2023-07-17 14:03:47.810035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af787317717c'
down_revision = 'e04f09912951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'report', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='unique') # type: ignore
    # ### end Alembic commands ###
