"""remove column from table

Revision ID: c2010fea1867
Revises: 1c3fcbc15477
Create Date: 2023-08-31 14:35:01.377046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2010fea1867'
down_revision = '1c3fcbc15477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'positive_language_percent')
    op.drop_column('section', 'constructive_language_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('constructive_language_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('section', sa.Column('positive_language_percent', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
