"""empty message

Revision ID: d7e097bdb926
Revises: a2b4b15fd4ff
Create Date: 2023-07-31 17:23:40.128565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e097bdb926'
down_revision = 'a2b4b15fd4ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
