"""Add stage to report

Revision ID: e04f09912951
Revises: 823ef3f899d1
Create Date: 2023-07-14 14:13:09.209039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04f09912951'
down_revision = '823ef3f899d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('stage', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'stage')
    # ### end Alembic commands ###
